CREATE TABLE beatmapsets (
    beatmapset_id INT NOT NULL PRIMARY KEY,
    artist VARCHAR(64) NOT NULL,
    artist_unicode NVARCHAR(64) NOT NULL,
    covers JSON NOT NULL,
    creator VARCHAR(64) NOT NULL,
    favourite_count INT NOT NULL,
    nsfw BOOLEAN NOT NULL,
    osu_play_count INT NOT NULL,
    preview_url VARCHAR(256) NOT NULL,
    source VARCHAR(64) NOT NULL,
    title VARCHAR(64) NOT NULL,
    title_unicode NVARCHAR(64) NOT NULL,
    mapper_id INT NOT NULL,
    mapper_name VARCHAR(64) NOT NULL,
    video BOOLEAN NOT NULL,
    download_disabled BOOLEAN NOT NULL,
    availability_information VARCHAR(2048) NULL,
    bpm FLOAT NOT NULL,
    can_be_hyped BOOLEAN NOT NULL,
    discussion_locked BOOLEAN NOT NULL,
    current_hype INT NULL,
    required_hype INT NULL,
    is_scoreable BOOLEAN NOT NULL,
    legacy_thread_url VARCHAR(256) NOT NULL,
    current_nominations INT NOT NULL,
    required_nominations INT NOT NULL,
    ranked_status INT NOT NULL,
    storyboard BOOLEAN NOT NULL,
    tags VARCHAR(256) NOT NULL,
    osu_submitted_at DATETIME NOT NULL,
    osu_updated_at DATETIME NOT NULL,
    osu_ranked_at DATETIME NULL,
    status VARCHAR(16) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT NOW(),
    updated_at DATETIME NOT NULL DEFAULT NOW()
);
