CREATE TABLE beatmaps (
    beatmap_id INT NOT NULL PRIMARY KEY,
    md5_hash CHAR(32) NOT NULL UNIQUE,
    set_id INT NOT NULL,
    mode INT NOT NULL,
    `convert` TINYINT(1) NOT NULL,
    od SMALLINT NOT NULL,
    ar SMALLINT NOT NULL,
    cs SMALLINT NOT NULL,
    hp SMALLINT NOT NULL,
    bpm FLOAT(6, 3) NOT NULL,
    hit_length INT NOT NULL,
    total_length INT NOT NULL,
    count_circles INT NOT NULL,
    count_sliders INT NOT NULL,
    count_spinners INT NOT NULL,
    difficulty_rating FLOAT(6, 3) NOT NULL,
    is_scoreable TINYINT(1) NOT NULL,
    pass_count INT NOT NULL,
    play_count INT NOT NULL,
    version VARCHAR(255),
    created_by INT NOT NULL,
    ranked_status INT NOT NULL,
    status INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT NOW(),
    updated_at DATETIME NOT NULL DEFAULT NOW()
);
